# Generated by Django 3.0.5 on 2020-04-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0002_geeksmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='title',
        ),
    ]
