# Generated by Django 3.0.5 on 2020-04-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0005_auto_20200412_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(default='u', max_length=20),
        ),
    ]
