# Generated by Django 3.0.5 on 2020-04-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GGuide', '0006_auto_20200412_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
