# Generated by Django 3.0.5 on 2020-04-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0012_auto_20200422_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='friends',
        ),
    ]
