# Generated by Django 3.0.5 on 2020-04-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0009_article_author'),
        ('GGuide', '0016_auto_20200422_1449'),
    ]

    operations = [
    ]
