# Generated by Django 3.0.5 on 2020-04-25 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0018_slug_20200425_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
