# Generated by Django 3.0.5 on 2020-04-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0025_user_ForeignKey'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='article_images'),
        ),
    ]
