# Generated by Django 3.0.5 on 2020-04-29 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GGuide', '0026_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
