# Generated by Django 3.0.5 on 2020-05-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0027_ProfileModel_friends_related_name'),
        ('GGuide', '0027_article_likes'),
    ]

    operations = [
    ]
