# Generated by Django 3.0.6 on 2020-05-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0029_slug_and_likes_for_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
    ]
