# Generated by Django 3.0.6 on 2020-05-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GGuide', '0032_comments_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parent',
            new_name='reply',
        ),
    ]
